# Generated by Django 3.2.13 on 2022-06-19 14:51

from django.db import migrations, models
import django.db.models.deletion
import malaria.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('user', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='hosptals', serialize=False, to='authentication.user')),
                ('name', models.CharField(default=' ', max_length=200)),
                ('email', models.EmailField(default=' ', max_length=100)),
                ('city', models.CharField(default=' ', max_length=100)),
                ('sub_city', models.CharField(default=' ', max_length=100)),
                ('phone', models.CharField(default=' ', max_length=20)),
                ('woreda', models.CharField(default=' ', max_length=10)),
                ('isActive', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=100)),
                ('sex', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=20)),
                ('sub_city', models.CharField(max_length=100)),
                ('woreda', models.CharField(max_length=10)),
                ('bmi', models.FloatField(max_length=5)),
                ('temperature', models.FloatField(max_length=5)),
                ('blood_pressure', models.FloatField(max_length=5)),
                ('rbc_count', models.FloatField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='RegisteredPersonnel',
            fields=[
                ('user', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='personnel', serialize=False, to='authentication.user')),
                ('name', models.CharField(default=' ', max_length=200)),
                ('email', models.EmailField(default=' ', max_length=200)),
                ('phone', models.CharField(default=' ', max_length=20)),
                ('city', models.CharField(default=' ', max_length=100)),
                ('sub_city', models.CharField(default=' ', max_length=100)),
                ('woreda', models.CharField(default=' ', max_length=10)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to=malaria.models.upload_to)),
                ('description', models.TextField(default=' ', max_length=500)),
                ('isActive', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='malaria.hospital')),
            ],
        ),
        migrations.CreateModel(
            name='RequestDiagnostic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(default='Pending', max_length=100)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Doctor', to='malaria.registeredpersonnel')),
                ('lab_technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Lab_Technician', to='malaria.registeredpersonnel')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='malaria.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=200)),
                ('instruction', models.CharField(max_length=200)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='malaria.registeredpersonnel')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='malaria.patient')),
            ],
        ),
    ]
