# Generated by Django 3.2.13 on 2022-06-17 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('malaria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registeredpersonnel',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
